### Getting started with OpenCV and Python

In [1]:
#importing libraries
import numpy as np
import cv2

In [2]:
#reading and diplaying images
img=cv2.imread("butterfly.jpg")                #reading using imread
cv2.namedWindow("Butterfly",cv2.WINDOW_NORMAL) #namedwindow with normalwindow placeholder
cv2.imshow("Butterfly",img)                    #diplaying the image in the same named window
cv2.waitKey(0)                                 #window will be opened until the user presses any key
cv2.destroyAllWindows()                        #destroying all the opened windows

### Access and Understand Pixel data

In [3]:
#to see the array of pixels in the image
print("Pixels in an image :\n",img)         

Pixels in an image :
 [[[ 57  91  54]
  [ 52  86  49]
  [ 44  78  41]
  ...
  [165 149 136]
  [172 150 144]
  [178 153 151]]

 [[ 55  89  52]
  [ 49  83  46]
  [ 41  75  38]
  ...
  [163 150 142]
  [171 151 150]
  [176 153 157]]

 [[ 53  87  50]
  [ 47  81  44]
  [ 37  74  36]
  ...
  [163 152 155]
  [169 153 164]
  [173 156 169]]

 ...

 [[ 47 124  62]
  [ 51 124  62]
  [ 59 123  63]
  ...
  [111 229 216]
  [110 228 210]
  [ 88 207 186]]

 [[ 45 122  60]
  [ 49 122  60]
  [ 57 121  62]
  ...
  [108 226 213]
  [110 229 214]
  [ 88 210 194]]

 [[ 45 124  61]
  [ 51 124  62]
  [ 60 124  65]
  ...
  [103 221 208]
  [104 224 213]
  [ 92 214 203]]]


In [4]:
print("Type of Image:",type(img))                      #type of image-numpy
print("length of an image(rows):",len(img))            #number of rows
print("length of an image(columns):",len(img[0]))      #number of columns
print("length of an image(channels):",len(img[0][0]))  #number of channels
print("size of an image:",img.size)                    #number of elements in an image array
print("shape of an image:", img.shape)                 #shape of a image
print("dtype:",img.dtype)                              #data type of the ekement in array

Type of Image: <class 'numpy.ndarray'>
length of an image(rows): 217
length of an image(columns): 300
length of an image(channels): 3
size of an image: 195300
shape of an image: (217, 300, 3)
dtype: uint8


In [5]:
print("To access the single channel of an image:\n",img[:,:,0])
print("\n")
print("To access all the channels in the single pixel of an image:\n",img[0,0,:])

To access the single channel of an image:
 [[ 57  52  44 ... 165 172 178]
 [ 55  49  41 ... 163 171 176]
 [ 53  47  37 ... 163 169 173]
 ...
 [ 47  51  59 ... 111 110  88]
 [ 45  49  57 ... 108 110  88]
 [ 45  51  60 ... 103 104  92]]


To access all the channels in the single pixel of an image:
 [57 91 54]


### Datatypes and structures

In [6]:
#black
black=np.zeros([150,200,1],'uint8')
cv2.imshow("Black",black)
print(black[0,0,:])

#black
ones=np.ones([150,200,3],'uint8')
cv2.imshow("Ones",ones)
print(ones[0,0,:])

#white
white=np.ones([150,200,3],'uint16')
white*=(2**16-1)
cv2.imshow("White",white)
print(white[0,0,:])

#blue
blue = ones.copy()
blue[:,:]=(255,0,0)
cv2.imshow("Blue",blue)
print(blue[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[0]
[1 1 1]
[65535 65535 65535]
[255   0   0]


### Image types and color channels

In [7]:
#read an image and display
img=cv2.imread("butterfly.jpg")
cv2.namedWindow("Butterfly",cv2.WINDOW_NORMAL)
cv2.imshow("Butterfly",img)
cv2.moveWindow("Butterfly",0,0)
#store height,width and channel in the variable respectively
height,width,channel= img.shape
#split the channels in the image as the separate components
b,g,r=cv2.split(img)

#create an empty array of mentioned size and show the different channel separately
rgb_split = np.empty([height,width*3,channel],'uint8')
rgb_split[:,0:width]=cv2.merge([b,b,b])
rgb_split[:,width:width*2]=cv2.merge([g,g,g])
rgb_split[:,width*2:width*3]=cv2.merge([r,r,r])
cv2.imshow("Channel",rgb_split)
#movewindow wil help to show all the images in an arranged way based on x and y value
cv2.moveWindow("Channel",0,height+20)
#hue (all color),saturation(how saturated the color is) and value(brightness or luminous of the color)
hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)          #convertingbgr color to hsv
h,s,v=cv2.split(hsv)                             #split and concatenating horizantally
hsv_split=np.concatenate((h,s,v),axis=1)
cv2.imshow("Split hsv",hsv_split)
cv2.moveWindow("Split hsv",0,height+height+40)


cv2.waitKey(0)
cv2.destroyAllWindows()

### Pixel Manipulation and Filtering

In [8]:
#reading and displaying the image
img=cv2.imread("butterfly.jpg")
cv2.namedWindow("Butterfly",cv2.WINDOW_NORMAL)
cv2.imshow("Butterfly",img)
cv2.moveWindow("Butterfly",0,0)
#converting to gray image
gray=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
cv2.imshow("Gray",gray)
cv2.moveWindow("Gray",width+20,0)
#split the each channel using arraying slicing(this method is more efficient than cv2.split(img))
r=img[:,:,0]
g=img[:,:,1]
b=img[:,:,2]
#merging all together along with transparency(alpha channel) together at the end (g-to make non green parts of the image transparent)
rgba=cv2.merge([r,g,b,g])
cv2.imwrite('rgba.png',rgba) #should save it as png not jpg as jpg doesnt support transparency


cv2.waitKey(0)
cv2.destroyAllWindows()

### Blur, dilation and erosion
[Click here to learn about erosion and dilation](https://www.youtube.com/watch?v=2LAooUu1IjQ)

[click here to learn the difference](https://www.geeksforgeeks.org/difference-between-dilation-and-erosion/)



In [9]:
#reading and displaying the image
image=cv2.imread("noise.jpg")
cv2.namedWindow("Original",cv2.WINDOW_NORMAL)
cv2.imshow("Original",image)

#gaussian blur
blur=cv2.GaussianBlur(image,(5,5),0)
cv2.imshow("Blur",blur)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

#dilation-1 if any of the structuring element is 1
#erosion - 1 only if all the structuring elements are 1
#erosion and dilation
kernel=np.ones((5,5),'uint8')
erode=cv2.erode(gray,None,iterations=2)
dilate=cv2.dilate(gray,None,iterations=1)

cv2.imshow("Dilation",dilate)
cv2.imshow("Erosion",erode)

cv2.waitKey(0)
cv2.destroyAllWindows()

### Scale and Rotate Images

In [10]:
img=cv2.imread("butterfly.jpg")
cv2.namedWindow("Butterfly",cv2.WINDOW_NORMAL)
#scaling
img_half=cv2.resize(img,(100,0),fx=0.5,fy=0.5)
img_stretch=cv2.resize(img,(400,400))
img_stretch_near=cv2.resize(img,(400,400),interpolation=cv2.INTER_NEAREST)

cv2.imshow("Butterfly",img)
cv2.imshow("Butterfly_half_sized",img_half)
cv2.imshow("Butterfly_stretch",img_stretch)
cv2.imshow("Butterfly_stretch_near",img_stretch_near)

cv2.moveWindow("Butterfly",0,0)
cv2.moveWindow("Butterfly_half_sized",300,0)
cv2.moveWindow("Butterfly_stretch",450,0)
cv2.moveWindow("Butterfly_stretch_near",800,0)
#rotating
height = img.shape[0]
width = img.shape[1]
(cX,cY) = (width//2,height//2)

M=cv2.getRotationMatrix2D((0,0),-30,1)
rotated=cv2.warpAffine(img,M,(width,height))
cv2.imshow("rotated",rotated)
cv2.moveWindow("rotated",0,height)

M1=cv2.getRotationMatrix2D((cX,cY),-30,1)
rotated_center=cv2.warpAffine(img,M1,(width,height))
cv2.imshow("rotated_center",rotated_center)
cv2.moveWindow("rotated_center",300,height)


cv2.waitKey(0)
cv2.destroyAllWindows()

### Simple and Adaptive Thresholding

In [29]:
bw =cv2.imread('sudoku.jpg',0)
height,width = bw.shape[0:2]
cv2.imshow("Original BW",bw)

binary=np.zeros([height,width,1],'uint8')
thresh=75
for row in range(0,height):
    for col in range(0,width):
        if bw[row][col]>thresh:
            binary[row][col]=255
cv2.imshow("Slow Binary",binary)
            
ret,thresh=cv2.threshold(bw,thresh,255,cv2.THRESH_BINARY)
cv2.imshow("Simple Threshold",thresh)

thresh_adapt=cv2.adaptiveThreshold(bw,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,115,1)
cv2.imshow("Adaptive Threshold",thresh_adapt)


cv2.waitKey(0)
cv2.destroyAllWindows()


### Skin Detection

In [49]:
skin_image=cv2.imread("skin.jpeg",1)
hsv=cv2.cvtColor(skin_image,cv2.COLOR_BGR2HSV)
h=hsv[:,:,0]
s=hsv[:,:,1]
v=hsv[:,:,2]
hsv_split=np.concatenate((h,s,v),axis=1)
cv2.imshow("split HSV",hsv_split)

ret,min_sat=cv2.threshold(s,40,255,cv2.THRESH_BINARY)
cv2.imshow("Sat Filter",min_sat)

ret,max_hue=cv2.threshold(h,15,255,cv2.THRESH_BINARY_INV)
cv2.imshow("Hue Filter",max_hue)

final=cv2.bitwise_and(min_sat,max_hue)
cv2.imshow("final",final)
cv2.imshow("Original",skin_image)


cv2.waitKey(0)
cv2.destroyAllWindows()

